name: REALMWarpsandPorts
main: net.bunnehrealm.warpsandports.MainClass
version: 1.0
description: >
            Create Warps and Portals!
commands:

  warp:
        description: Teleports you to a warp.
  wnp:
        description: Commands for warps.
  home:
        description: Sends you home.
  sethome:
        description: Sets your Home.
  tp:
        description: Teleports you to another player, or teleports one player to another.
  tphere:
        description: Teleports a player to you.
  tpall:
        description: Teleport all players to you.
  